# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default

development:
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: push_notification